// Copyright 2010-2014 Spraylight GmbH

#ifndef __MURL_I_ENUMS_DEBUG_H__
#define __MURL_I_ENUMS_DEBUG_H__

#include "murl_enum.h"

namespace Murl
{
    namespace IEnums
    {
        /**
         * @addtogroup MurlDebugEnumerations
         * @brief Debug items enumerations.
         * @{
         */

        /**
         * @brief Available statistic items.
         */
        enum StatisticItem
        {
            /// No state.
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, NONE,                            0)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, FRAMES_PER_SECOND,               1 << 0)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, TICKS_PER_FRAME,                 1 << 1)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, TOTAL_TIME,                      1 << 2)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, GENERAL,                         STATISTIC_ITEM_FRAMES_PER_SECOND
                                               + STATISTIC_ITEM_TICKS_PER_FRAME
                                               + STATISTIC_ITEM_TOTAL_TIME)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, GRAPH_LOGIC_TRAVERSAL_TIME,      1 << 4)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, GRAPH_INPUT_TRAVERSAL_TIME,      1 << 5)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, GRAPH_OUTPUT_TRAVERSAL_TIME,     1 << 6)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, GRAPH_TRAVERSAL_TIME,            STATISTIC_ITEM_GRAPH_LOGIC_TRAVERSAL_TIME
                                               + STATISTIC_ITEM_GRAPH_INPUT_TRAVERSAL_TIME
                                               + STATISTIC_ITEM_GRAPH_OUTPUT_TRAVERSAL_TIME)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, LOGIC_TICK_PROCESSING_TIME,      1 << 8)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, LOGIC_FRAME_PROCESSING_TIME,     1 << 9)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, LOGIC_PROCESSING_TIME,           STATISTIC_ITEM_LOGIC_TICK_PROCESSING_TIME
                                               + STATISTIC_ITEM_LOGIC_FRAME_PROCESSING_TIME)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, GRAPH_INIT_TRAVERSAL_OBJECTS,    1 << 12)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, GRAPH_LOGIC_TRAVERSAL_OBJECTS,   1 << 13)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, GRAPH_INPUT_TRAVERSAL_OBJECTS,   1 << 14)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, GRAPH_OUTPUT_TRAVERSAL_OBJECTS,  1 << 15)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, GRAPH_TRAVERSAL_OBJECTS,         STATISTIC_ITEM_GRAPH_INIT_TRAVERSAL_OBJECTS
                                               + STATISTIC_ITEM_GRAPH_LOGIC_TRAVERSAL_OBJECTS
                                               + STATISTIC_ITEM_GRAPH_INPUT_TRAVERSAL_OBJECTS
                                               + STATISTIC_ITEM_GRAPH_OUTPUT_TRAVERSAL_OBJECTS)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, PHYSICS_PROCESSING_TIME,         1 << 20)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, VIDEO_PROCESSING_TIME,           1 << 21)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, SYSTEM_PROCESSING_TIME,          STATISTIC_ITEM_PHYSICS_PROCESSING_TIME
                                               + STATISTIC_ITEM_VIDEO_PROCESSING_TIME)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, VIDEO_PROCESSING_OBJECTS,        1 << 24)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, AUDIO_PROCESSING_OBJECTS,        1 << 25)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, SYSTEM_PROCESSING_OBJECTS,       STATISTIC_ITEM_VIDEO_PROCESSING_OBJECTS
                                               + STATISTIC_ITEM_AUDIO_PROCESSING_OBJECTS)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, RESOURCE_BYTES_ALLOCATED,        1 << 28)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, VIDEO_BYTES_ALLOCATED,           1 << 29)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, AUDIO_BYTES_ALLOCATED,           1 << 30)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, SYSTEM_BYTES_ALLOCATED,          STATISTIC_ITEM_RESOURCE_BYTES_ALLOCATED
                                               + STATISTIC_ITEM_VIDEO_BYTES_ALLOCATED
                                               + STATISTIC_ITEM_AUDIO_BYTES_ALLOCATED)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(STATISTIC_ITEM, ALL,                             STATISTIC_ITEM_GENERAL
                                               + STATISTIC_ITEM_GRAPH_TRAVERSAL_TIME
                                               + STATISTIC_ITEM_LOGIC_PROCESSING_TIME
                                               + STATISTIC_ITEM_GRAPH_TRAVERSAL_OBJECTS
                                               + STATISTIC_ITEM_SYSTEM_PROCESSING_TIME
                                               + STATISTIC_ITEM_SYSTEM_PROCESSING_OBJECTS
                                               + STATISTIC_ITEM_SYSTEM_BYTES_ALLOCATED)
        };
        MURL_DECLARE_ENUM_ACCESSOR(StatisticItem)

        /**
         * @brief Available items for debug/error tracing.
         */
        enum DebugOutputFunctionItem
        {
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, NONE,                0)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, TYPE,                1 << 0)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, RETURN_VALUE,        1 << 1)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, CALLING_CONVENTION,  1 << 2)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, NAMESPACE,           1 << 3)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, CLASS,               1 << 4)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, FUNCTION,            1 << 5)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, PARAMETERS,          1 << 6)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, MODIFIER,            1 << 7)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, LINE,                1 << 8)
            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, USER,                1 << 9)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, ALL,                 DEBUG_OUTPUT_FUNCTION_ITEM_TYPE
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_RETURN_VALUE
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_CALLING_CONVENTION
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_NAMESPACE
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_CLASS
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_FUNCTION
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_PARAMETERS
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_MODIFIER
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_LINE
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_USER)

            MURL_DECLARE_ENUM_VALUE_PREDEFINED(DEBUG_OUTPUT_FUNCTION_ITEM, DEFAULT,             DEBUG_OUTPUT_FUNCTION_ITEM_CLASS
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_NAMESPACE
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_FUNCTION
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_LINE
                                               + DEBUG_OUTPUT_FUNCTION_ITEM_USER)
        };
        MURL_DECLARE_ENUM_ACCESSOR(DebugOutputFunctionItem)

        /** @} */
    }
}

#endif  // __MURL_I_ENUMS_DEBUG_H__
